### ISSUE TITLE
Feature Request: ANSI Paper Sizes

### ISSUE THREAD

**Issue by Saijin-Naib** [MarcoDuiker/QGIS_QuickPrint#10]
I'd love to be able to use this plugin with common/standard ANSI paper sizes, much like the two A_ paper sizes you've included.

Is this possible?

Thanks!

**Comment by MarcoDuiker** [comment]
I'm planning to do a release with some minor bug fixes.

I'll see if I can accommodate your request by adding an option to the settings dialog, so that the user can choose between paper size standards.

A pull request would also be very welcome.

**Comment by MarcoDuiker** [comment]
Please test the new version (you can install from this zip: https://github.com/MarcoDuiker/QGIS_QuickPrint/archive/3.5.0.zip)

**Comment by Saijin-Naib** [comment]
> I'm planning to do a release with some minor bug fixes.
> I'll see if I can accommodate your request by adding an option to the settings dialog, so that the user can choose between paper size standards.
> A pull request would also be very welcome.

I'll do my best to see what/how you added page sizes, and I'll try and include at least all the ANSI page sizes that the QGIS Print Composer includes. I have to learn first how you added them, however.

> Please test the new version (you can install from this zip: https://github.com/MarcoDuiker/QGIS_QuickPrint/archive/3.5.0.zip)

I get this failure when trying to import the above referenced Zip file into QGIS' plugin manager's load from zip function.


`Couldn't load plugin 'QGIS_QuickPrint-3.5.0' 
ModuleNotFoundError: No module named 'QGIS_QuickPrint-3' 
Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'QGIS_QuickPrint-3'
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.1-Noosa Noosa, 2468226bc9 
Python Path:
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThToolBox
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatial_query_with_values
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdaltools
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\karika
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomovetools
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AreaAlongVector
C:/OSGeo4W64/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\username\AppData\Local\gis4wrf\python37
C:\Users\username\AppData\Local\gis4wrf\python37\lib\site-packages
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GroupPointsWithinDistance
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Polygons_Pile
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RoadEmissionCalculator\lib
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SwapVectorDirection
`

**Comment by MarcoDuiker** [comment]
The zip you download contains a folder.

This folder (in the zip) must be renamed to `QuickPrint`.
The it will install as it should.

**Comment by MarcoDuiker** [comment]
I submitted a new version to the qgis plugins repo.

As soon as it is approved it will be available to you.
