### ISSUE TITLE
question about aligning map items

### ISSUE THREAD

**Issue by d3netxer** [MarcoDuiker/QGIS_QuickPrint#12]
Great code, it is helping me come up with a print layout for my project. 

One thing I am trying to do is align map items to the bottom of the map of my layout. In my case I would like to align the bottom of my legend with the bottom of the map border in my layout.

Do you have any idea how to do this? I have tried to set the reference point to the bottom left, but I cannot get it to to work for some reason. I also tried getting the height of my legend, ex: legend.sizeWithUnits().height()

but for some reason it only is able to print out the height after the map is exported. I was hoping to add the height of the legend item and add to it the margin between the bottom border of the map and the bottom of the page to set the correct height of the legend (assuming the reference point is the top left); but I cannot get this to work. Any help is appreciated.

**Comment by MarcoDuiker** [comment]
Thank you!

It's been ages that I wrote that code or looked at it. I really cannot help you on this one.

I think the QGIS dev mailing list is the best place to ask for help.

By the way, I avoid putting legends on automagically generated layouts like the plague. Legends always want to grow out of any box you provide for them. Putting the legend on a separate page is much easier and allow the desktop publishers to fool around with it as they like.
