### ISSUE TITLE
the North arrow is missing

### ISSUE THREAD

**Issue by libegon** [MarcoDuiker/QGIS_QuickPrint#4]
Very useful qgis plug-in ! 
It just misses the North arrow so that the map created respects all the cartography rules

**Comment by MarcoDuiker** [comment]
This is by design. Nowadays cartography rules are not that strict any more.
Only when a map is not oriented to the north a north arrow is mandatory.

As the plugin doesn't support other than north oriented map a north arrow is not necessary.

**Comment by MarcoDuiker** [comment]
By the way, you can of course use an image of a north arrow and put that as a logo on the page.
