### ISSUE TITLE
Uncaught NameError: global name 'item' is not defined


### ISSUE THREAD

**Issue by peter-shr** [MarcoDuiker/QGIS_QuickPrint#6]
Steps to reproduce
 1. First - klick Button
 2. Second - Browse to save path
 3. Third - klick Button Save

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\QuickPrint\quickprint.py", line 216, in run
    item.setStyle('Numeric')
NameError: global name 'item' is not defined

```
QuickPrint 0.4, QGIS 2.14.20-Essen on Windows 10

**Comment by MarcoDuiker** [comment]
Hmm, that's interesting.

I can't reproduce. On step 2 I get "Please type a file name" and I can't continue before I do so. If I do, and click save in the QuickPrint window, everything goes fine.

Furthermore (and more important), in the code of this quickprint plugin is no line 216 with `item.setStyle('Numeric')`.

Indeed such line is nowhere to be found in the code of this plugin. The name `item` is not used anywhere in the plugin.

Might it be that someone adapted the code?

Please reinstall the plugin straight from the QGIS plugins repository and see if the problem persists.

**Comment by peter-shr** [comment]
Dear Mr Duiker,
Sorry for the very late answer. At that time, I reacted too quickly to the error message. The mistake was made by myself.
I wanted to try to change the scale in the printout.
But it didn't work.

With best regards, Peter
(translated with www.deepl.com) 
 

    Am Donnerstag, 7. Dezember 2017, 17:32:37 MEZ hat Marco Duiker <notifications@github.com> Folgendes geschrieben:  
 
 
Hmm, that's interesting.

I can't reproduce. On step 2 I get "Please type a file name" and I can't continue before I do so. If I do, and click save in the QuickPrint window, everything goes fine.

Furthermore (and more important), in the code of this quickprint plugin is no line 216 with item.setStyle('Numeric').

Indeed such line is nowhere to be found in the code of this plugin. The name item is not used anywhere in the plugin.

Might it be that someone adapted the code?

Please reinstall the plugin straight from the QGIS plugins repository and see if the problem persists.
