### ISSUE TITLE
messageBar().pushMessage signature changed

### ISSUE THREAD

**Issue by olivierh65** [MarcoDuiker/QGIS_QuickPrint#7]
Hi,
using QGis 2.99.0-Master 6c64c5a586 there is an error on line :
self.iface.messageBar().pushMessage("Info", "Saved as pdf: %s" % self.dlg.pdfFileNameBox.displayText() ,self.iface.messageBar().INFO)
QgsMessageBar' object has no attribute 'INFO'

It seems that message level is now defined in Qgis class : 

void QgsMessageBar::pushMessage | ( | const QString & | text, Qgis::MessageLevel  level = Qgis::Info,
 int  duration = 5 )

**Comment by MarcoDuiker** [comment]
Thank you.
Indeed this error creeps up in the latest master.
fixed in commit  f17ed14cd72140ca591a9dbd600dc7be90a2bc47

I've uploaded version 3.4.1. with this fix to the QGIS plugin repo.
Once it is approved you'll be able to install the new version. Of course you can install from GitHub as well.
