### ISSUE TITLE
Actions en Toolbars are not removed when reloading/updating

### ISSUE THREAD

**Issue by rduivenvoorde** [MarcoDuiker/QGIS_QuickPrint#8]
When you upgrade the plugin the old actions/toolbars are not removed.

Seems like something is going wrong as the clean up of the plugins is being done in:

https://github.com/MarcoDuiker/QGIS_QuickPrint/blob/master/quick_print3.py#L200

via the actions in self.actions, but that only works when you CREATE those action via the add_action method:
https://github.com/MarcoDuiker/QGIS_QuickPrint/blob/master/quick_print3.py#L105

If you create your actions/toolbars yourself, you are also responsible for the cleanup.

**Comment by MarcoDuiker** [comment]
Fixed in version 3.4.2
